### ISSUE TITLE
Doesn’t work on WebKit

### ISSUE THREAD

**Issue by jessiejs** [micahlt/modchat-vue#11]
On WebKit on Safari on IPadOS, it just shows a white screen.

Webkit support is….. a little bit important.

Just a little.

No sarcasm here at all.

yeah, no, this should be pretty high priority.

That and it just not logging in for me on Firefox and Brave.

**Comment by micahlt** [comment]
For the moment development is paused, so please keep that in mind.  I've encountered no problems using WebKit besides notifications not working - are you able to give me a version/device?  Vue fully supports Safari, so I don't see why there should be an issue.

**Comment by ghost** [comment]
> On WebKit on Safari on IPadOS, it just shows a white screen.

@micahlt tells me that Safari/WebKit browsers are not supported.

@CodeLikeCrazE
