### ISSUE TITLE
Empty Messages

### ISSUE THREAD

**Issue by ghost** [micahlt/modchat-vue#4]
Currently, users are able to post empty messages. Should be an easy fix, though.

**Comment by illogicalapple** [comment]
I was able to post an empty message for a little bit, and then I wasn't, and then I was again.

**Comment by micahlt** [comment]
This was previously fixed, but now it's broken again.  The reasoning behind this is our XSS prevention protocols.  If the user inputs a disallowed character, it is simply removed.  This should be fixed relatively soon.

**Comment by ghost** [comment]
Sounds good, glad to hear this is actively being worked on.

**Comment by micahlt** [comment]
Fixed!
