### ISSUE TITLE
Could it be possible to create a normal sign-up with Github or something else?

### ISSUE THREAD

**Issue by AwesomePotato23** [micahlt/modchat-vue#5]
So basically, I was falsely reported and banned on Scratch, so I am wondering if you could possibly add a Github login or Google login?

**Comment by micahlt** [comment]
This won't be added since it would open Modchat to a variety of users outside the target base of Scratch.  This could be a huge problem for spam and moderation.  If you already have a Modchat Account (with your Scratch username and a different password) you should still be able to log in.
