### ISSUE TITLE
Duplicating messages after 5+ minutes off tab.

### ISSUE THREAD

**Issue by ghost** [micahlt/modchat-vue#6]
When the user is off the tab for 5+ minutes, it will rejoin the user but duplicate their messages. This bug is showcased in the image below.

![Screenshot 2021-12-22 174930](https://user-images.githubusercontent.com/96552473/147164221-8bcdce00-f223-4469-8965-a60c5fed6b34.png)

**Comment by micahlt** [comment]
@simplification10 This bug was fixed in commit 5536af7004d88119e776158ab61924ff06fe9cb4 🎉
